### ISSUE TITLE
Cant get download URL

### ISSUE THREAD

**Issue by stuCONNERS1983** [ich777/docker-xlink-kai-evolution#1]
---Checking if UID: 99 matches user---,
usermod: no changes,
---Checking if GID: 100 matches user---,
usermod: no changes,
---Setting umask to 022---,
---Checking for optional scripts---,
---No optional script found, continuing---,
---Starting...---,
---Checking if XLink Kai is installed and up-to-date---,
---Can't get download URL, putting server into sleep mode---,

I get the following error on startup of docker. If I restart the container, it deploys fine and works great. Im not sure if the container is starting before the network.

**Comment by ich777** [comment]
Applied a quick fix.
Check if you can connect to this URL in your browser: https://www.teamxlink.co.uk/connector/versionQuery.php?plain
If so the container should be able to get the donwload URL.

Keep in mind that the network is allready initialized in the container because you are using it from the host...

Please update the container and report back.

**Comment by stuCONNERS1983** [comment]
Updated to newest version. Works great thank you.
